info:
  contact: {}
paths:
  /index:
    get:
      responses:
        "200":
          description: OK
          schema:
            type: string
      tags:
      - 首页
  /user/info:
    get:
      responses:
        "200":
          description: code", "data"}
          schema:
            type: string
      tags:
      - 用户列表
swagger: "2.0"
